module.exports = {
  apps: [
    {
      name: 'insure-admin-service',
      script: './dist/app.js',
      instances: 'max',
      exec_mode: 'cluster',
      env: {
        NODE_ENV: 'production',
        PORT: 3001,
      },
      env_development: {
        NODE_ENV: 'development',
        PORT: 3001,
      },
      max_memory_restart: '1G',
      min_uptime: '10s',
      max_restarts: 10,
      restart_delay: 4000,
      autorestart: true,
      cron_restart: '0 3 * * *',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      error_file: './logs/pm2-error.log',
      out_file: './logs/pm2-out.log',
      log_file: './logs/pm2-combined.log',
      time: true,
      watch: false,
      ignore_watch: ['node_modules', 'logs', 'dist'],
      watch_options: {
        followSymlinks: false,
      },
      source_map_support: true,
      instance_var: 'INSTANCE_ID',
      exec_interpreter: 'node',
      exec_args: '--max-old-space-size=1024',
      kill_timeout: 5000,
      listen_timeout: 8000,
      node_args: '--experimental-modules',
      args: [],
      cwd: '.',
      interpreter: 'node',
      interpreter_args: [],
      output: './logs/pm2-out.log',
      pid_file: './pids/app.pid',
      vizion: false,
      post_update: ['npm install'],
      force: true,
    },
  ],

  deploy: {
    production: {
      user: 'deploy',
      host: ['your-server-ip'],
      ref: 'origin/main',
      repo: 'git@github.com:your-repo/insure-admin-service.git',
      path: '/var/www/insure-admin-service',
      'post-deploy': 'npm install && npm run build && pm2 reload ecosystem.config.js --env production',
      env: {
        NODE_ENV: 'production',
      },
    },
  },
};
